"""
Project Euler Problem #2
=========================

Each new term in the Fibonacci sequence is generated by adding the
previous two terms. By starting with 1 and 2, the first 10 terms will be:

                  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

Find the sum of all the even-valued terms in the sequence which do not
exceed four million.
"""

fibonacci = [1, 2]
i = 1
sum = 2

while True:
    next_term = fibonacci[i] + fibonacci[i-1]
    
    if next_term > 4000000:
        break
    
    fibonacci.append(next_term)
    
    if next_term % 2 == 0:
        sum += next_term

    i += 1

print sum
