"""
Project Euler Problem #12
==========================

The sequence of triangle numbers is generated by adding the natural
numbers. So the 7^th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 =
28. The first ten terms would be:

                 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

   1: 1
   3: 1,3
   6: 1,2,3,6
  10: 1,2,5,10
  15: 1,3,5,15
  21: 1,3,7,21
  28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five
divisors.

What is the value of the first triangle number to have over five hundred
divisors?
"""
import math

def factors(x):
    #return [i for i in range(1, x+1) if x%i == 0]
    
    count = 1
    for i in range(2, x+1):
        if  x % i == 0:
            count += 1
    return count

t_nums = [1,3,6]

def triangleNumber(n):
    #return sum(range(1, n+1));
    
    if len(t_nums) < n:
        t_nums.append(t_nums[n-2] + n)
    return t_nums[n-1]
    
'''
print triangleNumber(7);
print triangleNumber(10);
'''
#print factors(triangleNumber(7))

i = 1
target = 50

while(True):
    candidate = triangleNumber(i)
    divisors = factors(candidate)
    if divisors > target:
        print candidate
        quit()
    i += 1
'''

while(True):
    i = raw_input()
    candidate = triangleNumber(int(i))
    divisors = factors(candidate)
    print candidate, divisors
'''
