"""
Project Euler Problem 44
========================

Pentagonal numbers are generated by the formula, P[n]=n(3n-1)/2. The first
ten pentagonal numbers are:

               1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P[4] + P[7] = 22 + 70 = 92 = P[8]. However, their
difference, 70 - 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, P[j] and P[k], for which their sum
and difference is pentagonal and D = |P[k] - P[j]| is minimised; what is
the value of D?
"""
import math

def P(n):
    return n*(3*n-1) / 2

# Referencing:
# http://www.mathblog.dk/project-euler-44-smallest-pair-pentagonal-numbers/
# Inverse function of P
def isP(n):
    index = (math.sqrt(1+24*n) + 1.0)/6.0
    return index == int(index)

found = False
n = 1
while not found:
    for i in range(n, 1, -1):
        k = P(n)
        j = P(i)
        if isP(k-j) and isP(k+j):
            print k-j
            found = True
    n += 1
